name: MCRaidz
version: '1.0-DEV'
description: "The main plugin for MCRaidz, a pvp based gamemode on Minebo."
authors: ["Ian Rich"]
main: net.minebo.mcraidz.MCRaidz
soft-depend: ["PlaceholderAPI", "kRegions"]
api-version: '1.20'
